theme: jekyll-theme-minimal
title: Data  Projects
description: This repository is the data-related portfolio repository I created through self-directed learning. The repository contains Data Engineering, Data Analysis, Machine learning, Computer Vision, NLP, A/B testing, and other projects.
# logo: smlal.jpg
show_downloads: true
footer-links:
  email: smlalene@gmail.com
  github: sam23121
  linkedin: https://www.linkedin.com/in/samuel-alene-230309215/
